Added base connections between two sides
ValeryDrozd/Astrology-Social-Network pull request #6
Opened 2021-03-25 06:09 UTC by MedvedMichael

2021-03-25 07:48 UTC, nosovk commented on client/src/socket.tsx
> +  private socket = new Client('ws://localhost:3001');
env?

2021-03-25 07:50 UTC, nosovk commented on server/src/helpers/json-rpc.utils.ts
> +} from '../../../client/src/interfaces/json-rpc';
path alias?

2021-03-25 07:50 UTC, nosovk commented on server/src/modules/google/google.strategy.ts
> +      callbackURL: 'http://localhost:3001/google/redirect',
env

2021-03-31 13:31 UTC, MedvedMichael commented on server/src/modules/google/google.strategy.ts
> +      callbackURL: 'http://localhost:3001/google/redirect',
Module become useless

2021-04-01 05:52 UTC, nosovk commented on client/src/App.css
> +  min-width: none;height: 100vh;
better to check stylelint, to avoide things like that

2021-04-01 05:52 UTC, nosovk commented on client/src/components/chat-block/chat-block.tsx
> +    ? currentChat?.messageList.map((message, index) => (
currentChat?.messageList?.map
?

2021-04-01 05:52 UTC, nosovk commented on client/src/components/chat-block/chat-block.tsx
> +    if (newMessageText !== undefined && newMessageText !== '') {
unite in one check?

2021-04-01 05:52 UTC, nosovk commented on client/src/components/registration-block/registration-block.tsx
> +import React, { useState } from 'react';
React could be removed

2021-04-01 05:52 UTC, nosovk commented on client/src/components/registration-block/styles.tsx
> +  font-size: calc(3vw + 2rem);
если мы используем viewports нужно ограничивать max\min состояние. Тут высота зависит от ширины экарна, что может привести к странным еффектам на большом экране в ширину к примру

2021-04-01 05:52 UTC, nosovk commented on client/src/helpers/get-fingerprint.ts
> +        preprocessor: (key: string, value: string): string => {
probably useless

2021-04-01 05:52 UTC, nosovk commented on client/src/helpers/get-fingerprint.ts
> +export default function getFingerprint(): Promise<string> {
wrap in lazy load, only if no present in session store

2021-04-01 05:52 UTC, nosovk commented on client/src/pages/chatPage/chatPage.tsx
> +import React, { FormEvent, useState } from 'react';
React mot needed to import

2021-04-01 05:52 UTC, nosovk commented on client/src/pages/loginPage/loginPage.tsx
> +        'http://localhost:3001/auth/google',
env?

2021-04-01 05:52 UTC, nosovk commented on client/src/pages/loginPage/loginPage.tsx
> +    } catch (error) {}
show error to user?

2021-04-01 05:52 UTC, nosovk commented on client/src/pages/loginPage/loginPage.tsx
> +          fingerprint: await getFingerprint(),
call it only if not present in session storage

2021-04-01 05:52 UTC, nosovk commented on client/src/pages/loginPage/loginPage.tsx
> +      history.push('/chat');
as far I remember React have native way for that action, but mayby not?

2021-04-01 05:54 UTC, nosovk commented on client/src/pages/loginPage/loginPage.tsx
> +          id="email"
probably id should be avoided

2021-04-01 05:55 UTC, nosovk commented on client/src/services/auth.service.ts
> +      withCredentials: true,
fetch has the same option

2021-04-01 05:56 UTC, nosovk commented on client/src/services/auth.service.ts
> +    'http://localhost:3001/auth/login',
env var?

2021-04-01 06:03 UTC, nosovk commented on client/src/stores/store.ts
> +    this.messagesQueue = JSON.parse(localStorageValue);
JSON.parse could throw an exception. Wrap to try catch, or implement safeParse

2021-04-01 06:04 UTC, nosovk commented on server/db/tables.sql
> +	"sex" VARCHAR(1) CHECK ("sex" IN ('F','M'))
why not bool?

2021-04-01 06:06 UTC, nosovk commented on server/db/tables.sql
> +	"compatibility" REAL,
store as money, in int

2021-04-01 06:07 UTC, nosovk commented on server/db/tables.sql
> +	"password" VARCHAR (255)
check max hash length

2021-04-01 06:10 UTC, nosovk commented on server/src/helpers/send-tokens-pair.ts
> +    maxAge: 5.184e9,
store in readable format?

2021-04-01 06:10 UTC, nosovk commented on server/src/helpers/send-tokens-pair.ts
> +    httpOnly: true,
secure: true

2021-04-01 06:11 UTC, nosovk commented on server/src/main.ts
>    const port = process.env.PORT ? process.env.PORT : 3001;
`process.env.PORT ?? 30001`

2021-04-01 06:12 UTC, nosovk commented on server/src/adapters/json-rpc-ws-adapter.ts
> +} from '../../../client/src/interfaces/json-rpc';
add alias path to avoide .././../../

2021-04-01 06:20 UTC, nosovk commented on server/src/modules/chats/my-chats.ts
> +WHERE NOT cu."userID" = $1`;
LIMIT 1?

2021-04-01 06:22 UTC, nosovk commented on server/src/modules/chattings/chattings.gateway.ts
> +      sendResponse({ ok: false, code: -32600, message: 'INVALID TOKEN' });
store jso rpc codes as ENUM

2021-04-01 06:25 UTC, nosovk commented on server/src/modules/chattings/chattings.service.ts
> +  private messages: Message[] = [
some mock?

2021-04-15 05:33 UTC, nosovk commented on client/src/components/chat-block/chat-block.tsx
> +import React, { useEffect, useRef, useState } from 'react';
React may be ommited, 
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

2021-04-15 05:34 UTC, nosovk commented on client/src/components/chat-block/chat-block.tsx
> +import Message from '../../interfaces/message';
../../ more then one isn't good, better use alias from root

2021-04-15 05:37 UTC, nosovk commented on client/src/components/scroll-list/scroll-list.tsx
> +  const onWheel = ({ deltaY }: React.WheelEvent<HTMLUListElement>): void => {
debounce?

2021-04-15 05:41 UTC, nosovk commented on client/src/index.css
> +    -apple-system,
apple-system probably should be fallback?

2021-04-15 05:42 UTC, nosovk commented on client/src/interfaces/routes/auth-routes.ts
> +  fingerprint: string;
security over obscurity - dont name it fingerprint :)

2021-04-15 05:46 UTC, nosovk commented on client/src/stores/store.ts
> +      this.messagesQueue = JSON.parse(localStorageValue);
JSON.parse may throw....

2021-04-15 05:49 UTC, nosovk commented on server/db/tables.sql
> +	"zodiacID1" INT REFERENCES "ZodiacSigns" ON DELETE CASCADE,
reverse?

2021-04-15 06:02 UTC, nosovk commented on server/src/modules/auth/auth.service.ts
> +    const password = pass ? await this.scryptService.hash(pass) : undefined;
AuthProviderName instead

2021-04-15 06:03 UTC, nosovk commented on server/src/modules/auth/auth.service.ts
> +        userAgent ? userAgent : '',
userAgent ?= ''

2021-04-15 06:09 UTC, nosovk commented on server/src/modules/chattings/chattings.gateway.ts
> +      sendResponse({ ok: false, code: -32600, message: 'INVALID TOKEN' });
reviwe

2021-04-26 20:34 UTC, nosovk commented on client/src/components/profile-block/profile-block.tsx
> +        <AvatarImage src={user?.sex ? '/man.jpg' : '/women.jpg'} />
лучше такие штуки через css делать и класс (как bg image),  если у человека уже есть аватарка то поверх догружать его аватрку

2021-04-26 20:34 UTC, nosovk commented on client/src/components/profile-block/profile-block.tsx
> +          <DetailInfo>{user?.zodiacSign}</DetailInfo>
через ?? можно задать фолбек значения, они позволят кому-то не смотерть на пустые строки если что-то пойдет не так

2021-04-26 20:35 UTC, nosovk commented on client/src/components/profile-block/profile-block.tsx
>  import chatStore from '../../stores/store';
когда мы видим ../../ - более чем ../ то скорее всего просто кто-то забыл прописать алиасы к путям :)

2021-04-26 20:37 UTC, nosovk commented on client/src/pages/chatPage/chatPage.tsx
> +      (chatStore.user?.sex === null ||
может можно без === null?

2021-04-26 20:38 UTC, nosovk commented on client/src/pages/extraInfoPage/extraInfoPage.tsx
> +          return history.push('/users/' + user.userID);
лучше template string
`/users/${user.userID}`

2021-04-26 20:38 UTC, nosovk commented on client/src/pages/extraInfoPage/extraInfoPage.tsx
>          if (user?.birthDate && user?.sex !== null && user?.zodiacSign) {
могу понять зачем все время все 3 поля проверть? почему не достаточно проверять что юзер есть?

2021-04-26 20:39 UTC, nosovk commented on client/src/pages/extraInfoPage/extraInfoPage.tsx
>          setSex(user?.sex !== null ? (user.sex as boolean) : true);
мы уже выше проверили то же самое, зачем еще одна такая же проверка?

2021-04-26 20:42 UTC, nosovk commented on client/src/socket.tsx
> +    max_reconnects: 0,
хм, мы не будем реконектится в случае обрыва?

2021-04-26 20:43 UTC, nosovk commented on client/src/stores/store.ts
> +    if (Date.now() >= this.exp * 1000) {
лушче куда-то в контсанты с звучным именем вынести

2021-04-26 20:50 UTC, nosovk commented on server/src/adapters/json-rpc-ws-adapter.ts
> +    const message: JsonRpcRequest = JSON.parse(buffer.data);
нет проверки на то что в data json. а parse успешно кидает exception...

2021-04-26 20:52 UTC, nosovk commented on server/src/modules/auth/auth.service.ts
> +        userAgent ? userAgent : '',
ну тут же вроде то же самое осталось

2021-04-26 20:59 UTC, nosovk commented on server/src/modules/zodiac-signs/zodiac-signs.service.ts
> +  async getZodiacName(zodiacID: number): Promise<string | undefined> {
на самом то деле штуки вроде зодиака можно мемоизировать в мапу.... И не ходить каждый раз в бд

2021-04-26 21:00 UTC, nosovk requested changes
еще есть не закрытые комменты по PR

2021-05-15 15:56 UTC, merged